# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('partido', models.CharField(max_length=150, verbose_name='partido')),
            ],
        ),
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEleicao', models.IntegerField(verbose_name='CodigoEleição')),
                ('local', models.CharField(max_length=100, verbose_name='local')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeInicio')),
                ('dataEHoraDeTermino', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeTermino')),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('CPF', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleicao', to='evento.Eleicao')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='cargo')),
                ('quantidadeVaga', models.IntegerField(verbose_name='quantidadeVaga')),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatoVaga', to='evento.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Votar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[(models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='evento.Candidato'), models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='evento.Candidato')), (models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='evento.Candidato'), models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='evento.Candidato'))], max_length=150)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='evento.Candidato')),
                ('eleitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleitor', to='evento.Eleitor')),
            ],
        ),
        migrations.RemoveField(
            model_name='artigoautor',
            name='artigoCientifico',
        ),
        migrations.RemoveField(
            model_name='artigoautor',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='artigocientifico',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='realizador',
        ),
        migrations.RemoveField(
            model_name='eventocientifico',
            name='evento_ptr',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='tipoInscricao',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='pessoa_ptr',
        ),
        migrations.DeleteModel(
            name='ArtigoAutor',
        ),
        migrations.DeleteModel(
            name='ArtigoCientifico',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='EventoCientifico',
        ),
        migrations.DeleteModel(
            name='Inscricoes',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
        migrations.DeleteModel(
            name='PessoaJuridica',
        ),
        migrations.DeleteModel(
            name='TipoInscricao',
        ),
        migrations.AddField(
            model_name='eleitor',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Token', to='evento.Token'),
        ),
    ]
