# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20171120_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votar',
            name='voto',
        ),
        migrations.AddField(
            model_name='votar',
            name='Votou',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votar',
            name='votouemBranco',
            field=models.BooleanField(default=False, verbose_name='Consistência da frequência!?'),
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='candidato',
        ),
        migrations.AddField(
            model_name='vaga',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatoVaga', to='evento.Candidato'),
        ),
    ]
