# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20171120_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votar',
            name='votouemBranco',
            field=models.BooleanField(default=False, verbose_name='Voto em Branco?'),
        ),
    ]
